name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv run pytest -v -s