name: Integration Tests
on:
  push:
    branches:
      - master
jobs:
  integration:
    name: Run integration tests
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv run pytest tests/integration/ -v -s -m integration
        env:
          LAKEHOUSE_API_URL: ${{secrets.LAKEHOUSE_API_URL}}
